FROM golang:1.19

WORKDIR /app

COPY ./ /app

RUN go mod download && \
    go mod tidy && \
    go get github.com/githubnemo/CompileDaemon && \
    go install github.com/githubnemo/CompileDaemon

EXPOSE 8080

ENTRYPOINT CompileDaemon --build="go build cmd/server/main.go" --command=./main