basePath: /
definitions:
  model.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact:
    email: tiago.santana@gmail.com
    name: Tiago Sant'Ana
    url: https://github.com/tiagostn
  description: Example Golang REST API
  title: Go api using Gin with clean architecture
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: get hello world response
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Root
  /user:
    get:
      description: get default user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Default User
swagger: "2.0"
